kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: golang:1.13
    commands:
      - go test ./cmd/... ./internal/...
      - go vet ./cmd/... ./internal/...
  - name: build
    image: golang:1.13
    commands:
      - go build -o build/drone-helm cmd/drone-helm/main.go
  - name: publish_linux_arm64
    image: plugins/docker
    settings:
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: plugin_repo
      dockerfile: Dockerfile
    when:
      event: [ tag, push ]
